# Site settings
title: techwoods
description: A blog about lorem ipsum dolor sit amet
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://westwoods.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: westwoods
user_description: 안녕하세요
user_title: westwoods
email: kdw8681@naver.com
twitter_username: null
github_username:  westwoods
gplus_username:  null

# Google-analytics
google-analytics:
  id: kdw8681

exclude: ['package.json', 'src' , 'node_modules']
