

title: techwoods
description: A blog about lorem ipsum dolor sit amet
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://westwoods.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: westwoods # your name
bio:   # your bio
email:
email_md5: # md5 hash of your email
twitter_username:
github_username: westwoods

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
